parameters:
    sitemap.generator.class:   Presta\SitemapBundle\Sitemap\Generator
    
    sitemap.section.class:     Presta\SitemapBundle\Sitemap\Section
    sitemap.url.class:         Presta\SitemapBundle\Sitemap\Url
    sitemap.url.image.class:   Presta\SitemapBundle\Sitemap\Url\Image
    sitemap.builder.class:     Presta\SitemapBundle\Sitemap\Builder
    

services:
    sitemap.generator:
        class:        '%sitemap.generator.class%'
        arguments:    [@sitemap.builder, @event_dispatcher, @router]   
    sitemap.builder:
        class:        '%sitemap.builder.class%'
        arguments:    ['%sitemap.builder.root_url%']   
        