language: php

php:
    - 7.0
    - 7.1

matrix:
    include:
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*@beta SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.1
          env: SYMFONY_VERSION=3.4.*@beta SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.1
          env: SYMFONY_VERSION=4.0.*@beta SYMFONY_DEPRECATIONS_HELPER=strict

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$PHPCS" = "yes" ]; then pear install pear/PHP_CodeSniffer; fi
    - if [ "$PHPCS" = "yes" ]; then phpenv rehash; fi
    - if [ "$PHPCS" != "yes"]; then composer selfupdate; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: if [ "$PHPCS" != "yes" ]; then composer update --prefer-dist; fi

script:
    - if [ "$PHPCS" != "yes" ]; then phpunit --coverage-text; fi
    - if [ "$PHPCS" = "yes" ]; then phpcs --ignore=/vendor/*,/Tests/app/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .; fi

notifications:
    email:
        - yeugone@prestaconcept.net
