language: php

php:
    - 5.6
    - 7.0
    - hhvm

matrix:
    include:
        - php: 5.6
          env: SYMFONY_VERSION=2.3.*
        - php: 5.6
          env: SYMFONY_VERSION=2.7.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=2.8.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 5.6
          env: SYMFONY_VERSION=3.0.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.0
          env: SYMFONY_VERSION=3.2.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.0
          env: SYMFONY_VERSION=3.3.* SYMFONY_DEPRECATIONS_HELPER=strict
        - php: 7.0
          env: SYMFONY_VERSION=3.4.*@dev SYMFONY_DEPRECATIONS_HELPER=strict
    allow_failures:
        - env: SYMFONY_VERSION=3.4.*@dev

env:
    global:
        - SYMFONY_DEPRECATIONS_HELPER=weak

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - if [ "$PHPCS" = "yes" ]; then pear install pear/PHP_CodeSniffer; fi
    - if [ "$PHPCS" = "yes" ]; then phpenv rehash; fi
    - if [ "$PHPCS" != "yes"]; then composer selfupdate; fi
    - if [ "$SYMFONY_VERSION" = "3.2.*" ] || [ "$SYMFONY_VERSION" = "3.3.*" ] || [ "$SYMFONY_VERSION" = "3.4.*@dev" ]; then composer require --no-update twig/twig:~2.0; fi
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony:${SYMFONY_VERSION}; fi

install: if [ "$PHPCS" != "yes" ]; then composer update --prefer-dist; fi

script:
    - if [ "$PHPCS" != "yes" ]; then phpunit --coverage-text; fi
    - if [ "$PHPCS" = "yes" ]; then phpcs --ignore=/vendor/*,/Tests/app/* --extensions=php --encoding=utf-8 --standard=PSR2 -np .; fi

notifications:
    email:
        - yeugone@prestaconcept.net
